### ISSUE TITLE
The command and subcommand module can use each other.

### ISSUE THREAD

**Issue by portlek** [HSGamer/HSCore#35]
- The command module can contain sub command instance.
- When a player runs a command, the command will look at the subcommands.

**Comment by HSGamer** [comment]
I've separated them because I don't know how others will implement the commands (extends Command, CommandExecutor, etc). And some projects may not need to use sub-commands, like my projects BetterGUI and TopIn.

**Comment by portlek** [comment]
So It should be optional to add subcommands.

**Comment by HSGamer** [comment]
They can add it as a dependency and make their own commands. SubCommandManager is useful in those cases.
