### ISSUE TITLE
HSCore-sql

### ISSUE THREAD

**Issue by HSGamer** [HSGamer/HSCore#43]
This module to work with SQL

**Comment by portlek** [comment]
- It should use HikariCP

**Comment by portlek** [comment]
Bukkit has MySQL and SQLite drivers, but without bukkit, you can't run it as standalone so, you should make it under the bukkit module; otherwise, you can add the drivers as dependencies, but they have 2-3mb~ size so.

**Comment by portlek** [comment]
here is the recommend options for hikaricp if you want to use it;
https://github.com/Infumia/DB/blob/master/src/main/java/tr/com/infumia/db/Credentials.java

**Comment by HSGamer** [comment]
> here is the recommend options for hikaricp if you want to use it;
> https://github.com/Infumia/DB/blob/master/src/main/java/tr/com/infumia/db/Credentials.java

nice

**Comment by HSGamer** [comment]
> Bukkit has MySQL and SQLite drivers, but without bukkit, you can't run it as standalone so, you should make it under the bukkit module; on the other hand, you can add the drivers as dependencies, but they have 2-3mb~ size so.

currently I don't add the dependencies. I will leave the option for others. I'll think of a way around it soon
