### ISSUE TITLE
HSCore-ui and HSCore-bukkit-gui

### ISSUE THREAD

**Issue by HSGamer** [HSGamer/HSCore#46]
### Current Idea
* **`HSCore-ui`**
  * **Holder**
    * `Display create(UUID uuid)` create a display for the `uuid`
    * `void updateAll()` update all displays??
    * `void <T> addEventFunction(Class<T> event, Function<T> function)` add an event function
    * `void handleEvent(Object event)` run the function for the event
  * **Display**
    * `void init()` initialize the display
    * `void update()` update the display
  * ****
* **`HSCore-bukkit-gui`**
  * **Holder** (extend from `HSCore-ui`)
    * `void onOpen(openEvent)` handle the open event
    * `void onClick(clickEvent)` handle the click event
    * `void onClose(closeEvent)` hande the close event

**Comment by portlek** [comment]
- UI should be a common module for any Java project.
- bukkit-gui should have all types of UI. For example, A simple inventory UI, hopper UI, 3x3 container UIs, crafting table UI, etc.

**Comment by portlek** [comment]
- This project and class may help to an UI library [SmartInventory](https://github.com/portlek/SmartInventory/blob/master/src/main/java/io/github/portlek/smartinventory/content/BasicInventoryContents.java)

**Comment by HSGamer** [comment]
update the idea

**Comment by portlek** [comment]
- Use a design pattern called `observer` to design the update method.

Example usage for observer pattern [Observer](https://github.com/portlek/SmartInventory/tree/master/src/main/java/io/github/portlek/observer)

**Comment by portlek** [comment]
- Need to think about what should the common UI module does.
- The common module shouldn't do anything without other modules.
- The common module should have just interfaces and some envelope classes.

**Comment by HSGamer** [comment]
update

**Comment by portlek** [comment]
A UI designed with slots shouldn't be the only design in the UI module. for example, Minecraft bedrock edition has this
![image](https://user-images.githubusercontent.com/12835420/97783456-f5f71b00-1ba8-11eb-98c7-b4e95bddde19.png)
called custom forms
These forms haven't slots but they are UIs so, we should think that too.

**Comment by portlek** [comment]
The forms have inputs too.

**Comment by HSGamer** [comment]
The Bukkit module should be the only module that has slots in it. Others will be event-based.
