### ISSUE TITLE
Config module should separated from bukkit modules.

### ISSUE THREAD

**Issue by portlek** [HSGamer/HSCore#5]
It should not depend on the bukkit module. Because it basically file and configuration library. Also there is a bukkit-like configuration library json/yaml here https://github.com/Carleslc/Simple-YAML and for json here https://github.com/portlek/jsongration

I think this makes the config and extra-config module more independent so it can use on every Java project. The config module depends on bukkit like un-necessary.

**Comment by HSGamer** [comment]
I've been thinking of a standalone module for config for a while.
But since my projects are Bukkit plugins, I didn't do that.
I'll seperate them later when I havr time

**Comment by portlek** [comment]
Alright, I will open a pull request for that.
