### ISSUE TITLE
Make a module that can download addons from the url.

### ISSUE THREAD

**Issue by portlek** [HSGamer/HSCore#63]
Need more ideas.

**Comment by HSGamer** [comment]
make a repo that store the information of the addons, and maybe the direct link to download them ??

**Comment by portlek** [comment]
I guess there should be a server that stores all addons with the ids.

**Comment by portlek** [comment]
Similar to spring boot but just id and the file.

**Comment by HSGamer** [comment]
is this your idea?
https://github.com/BetterGUI-MC/Addon-List

**Comment by portlek** [comment]
Github releases are useful to store .jar files so maybe don't need a server.

**Comment by portlek** [comment]
> is this your idea?
> https://github.com/BetterGUI-MC/Addon-List

Actually yea something like that. Stores some addon information and URL to download it. And the addon module will download the addon from the given information and loads it.

**Comment by HSGamer** [comment]
Then it's easier. Because I've implemented it in BetterGUI.
Could be easy to add it here.

**Comment by portlek** [comment]
alright sounds good.

**Comment by HSGamer** [comment]
https://github.com/BetterGUI-MC/BetterGUI/tree/master/src/main/java/me/hsgamer/bettergui/downloader

**Comment by portlek** [comment]
yea that's enough I guess.
