### ISSUE TITLE
TOML support for config

### ISSUE THREAD

**Issue by HSGamer** [HSGamer/HSCore#69]
Need ideas

**Comment by portlek** [comment]
- Should be commentable.

**Comment by portlek** [comment]
I've already a TOML repository but it didn't finish yet. [here](https://github.com/portlek/tomlgration)

**Comment by portlek** [comment]
[TOML](https://github.com/toml-lang/toml)

**Comment by portlek** [comment]
[For Java](https://github.com/mwanji/toml4j)

**Comment by portlek** [comment]
```xml
<dependency>
    <groupId>io.github.portlek</groupId>
    <artifactId>tomlgration</artifactId>
    <version>1.0.0</version>
</dependency>
```
the usage same as the jsongration;
TomlConfiguration.load(File);

**Comment by HSGamer** [comment]
I gonna close this issue and create a new one for Commentable
