### ISSUE TITLE
TOML comment support

### ISSUE THREAD

**Issue by HSGamer** [HSGamer/HSCore#70]

**Comment by portlek** [comment]
- Make it like [Example](https://github.com/Carleslc/Simple-YAML/tree/master/Simple-Yaml/src/main/java/org/simpleyaml/configuration/comments)

**Comment by portlek** [comment]
Wait for the [issue](https://github.com/portlek/tomlgration/issues/7) to solve.

**Comment by HSGamer** [comment]
Close this as I changed the config module
