### ISSUE TITLE
Better Location and ItemStack serializable support.

### ISSUE THREAD

**Issue by portlek** [HSGamer/HSCore#98]
- ItemStack should be serialized and deserialized with a custom method, not the Bukkit one.
  - [ItemStackUtil](https://github.com/portlek/BukkitItemBuilder/blob/master/src/main/java/io/github/portlek/bukkititembuilder/util/ItemStackUtil.java)
  - [XItemStack](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XItemStack.java)
---
Done
- Locations should be covered with a class called Position that contains these fields and methods
  - world: String
  - x: double
  - y: double
  - z: double
  - yaw: float
  - pitch: float
  - get(): Location
    - Throw if Bukkit.getWorld(this.world) is null
    - returns new Location(Bukkit.getWorld(this.world, this.x, this.y, this.z, this.yaw, this.pitch))
  - serialize(): Map<String, Object>
  - static deserialize(Map<String, Object>): Position

**Comment by HSGamer** [comment]
close via https://github.com/HSGamer/HSCore/commit/45bc20ef4d3e2076063d67314aa3faebe4a75006
